### ISSUE TITLE
Iamport API 호출 건

### ISSUE THREAD

**Issue by giwonn** [YuDangTang/shopping#10]
안녕하세요. 아임포트 관련 글을 블로그에 작성했던 적이 있었는데요.([링크](https://l4279625.tistory.com/27))

저 글에 api 설명할 때 api호출 정보에 제 이메일을 적어놨었는데요.

11월 2일부터 아래와 같이 매일 꾸준히 이메일이 날라옵니다.
![image](https://user-images.githubusercontent.com/72638829/201529646-76dc176f-4fbd-4e14-96a7-50e5a1a9fb64.png)
![image](https://user-images.githubusercontent.com/72638829/201529612-8bd1a56c-d7f9-4486-8862-1b225b3db8c3.png)

주문 상품명에 `mieummieum`으로 작성되어 있는 코드를 찾아본 결과 이 레포지토리에서 해당 상품명을 발견하였습니다.

코드 상으로는 제 이메일이 적혀져 있지 않은 것으로 보입니다. 혹시 배포된 버전이 있는걸까요?
혹은 배포된 버전이 있다면 해당 배포 버전이 예전것인지 한번 확인 부탁드립니다 ㅠ

**Comment by dabin0513** [comment]
죄송합니다.... 현재 배포된 버전은 없고, 코드 상에 이메일이 적혀있었습니다.... 코드 테스트 중에 날아간 이메일인 것 같습니다.. 코드 수정했고 불편을 드려 죄송합니다 ㅜㅜ

**Comment by giwonn** [comment]
감사합니다! 좋은 하루 되세요!
